FILE_PATH = '/data/FlyingChairs/data'
LIST_PATH = '/data/list'

BATCH_SIZE = 4
IMAGE_HEIGHT = 384
IMAGE_WIDTH = 512
IMAGE_CHANNELS = 3
FLO_CHANNELS = 2

INITIAL_LEARNING_RATE = 1e-4
LOG_DIR = '/home/pyramid/flownet/'
MAX_STEPS = 1200000
